# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OwvggvXXvEX_dal0rKYXlG2riwQcqj1k
"""

# ----- CELL 1: Kill old servers -----
import subprocess, time
subprocess.run("kill -9 $(lsof -t -i:7860) 2>/dev/null || true", shell=True)
subprocess.run("pkill -f gradio 2>/dev/null || true", shell=True)
time.sleep(2)
print("Ports cleared!")

# ----- CELL 2: Install -----
!pip install gradio transformers Pillow matplotlib torch torchvision --quiet

# ----- CELL 3: Imports -----
import gradio as gr
import torch
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np
from PIL import Image
from transformers import pipeline
from datetime import datetime
import warnings
warnings.filterwarnings("ignore")
print("All imports OK")

# ----- CELL 4: Load Model -----
print("Loading model...")
classifier = pipeline("image-classification",
                      model="yangy50/garbage-classification", top_k=6)
scan_history = []
print("Model ready! Device:", "GPU" if torch.cuda.is_available() else "CPU")

# =============================================================
# FULL UI STRINGS - all 3 languages
# =============================================================
UI = {
    "en": {
        # Header
        "header_sub":    "AI Powered • Eco Focused • Future Ready",
        "header_desc":   "Helping a cleaner Earth through smart waste management.",
        "header_types":  "Waste Types",
        "header_langs":  "Languages",
        "header_powered":"Powered",
        "header_voice":  "Voice AI",
        # Dropdown label
        "lang_label":    "🌐 Select Language",
        "lang_hint":     "✨ Entire interface changes with language selection",
        # Tab names
        "tab_scan":      "🔬 SCAN WASTE",
        "tab_analytics": "📊 ANALYTICS",
        "tab_education": "🌱 ECO EDUCATION",
        "tab_about":     "ℹ️ ABOUT",
        # Scan tab
        "upload_label":  "📷 Upload or Capture Waste Image",
        "tab_upload":    "📁 Upload Image",
        "tab_webcam":    "📷 Webcam",
        "img_drop":      "Drop image here or click to upload",
        "img_webcam":    "Capture from Webcam",
        "btn_analyze":   "🔍 Analyze Waste Now",
        "btn_clear":     "🗑️ Clear",
        "result_label":  "🤖 AI Analysis Result",
        # Placeholder
        "placeholder":   "Upload an image and click Analyze",
        "placeholder2":  "JPG • PNG • JPEG • Webcam",
        # Analytics tab
        "analytics_title":"📈 Waste Analytics Dashboard",
        "chart_donut":   "🍩 Confidence Breakdown",
        "chart_gauge":   "🌱 Eco Score Gauge",
        "chart_dist":    "📊 Scan Distribution",
        "no_history":    "No scan history yet.",
        # Eco tips
        "tips_title":    "💚 Eco Education & Tips",
        "tip_water_t":   "Water",
        "tip_water_d":   "Turn off tap while brushing. Fix leaks promptly.",
        "tip_energy_t":  "Energy",
        "tip_energy_d":  "Switch to LED bulbs. Unplug idle devices.",
        "tip_green_t":   "Go Green",
        "tip_green_d":   "Plant trees. Start composting kitchen waste.",
        "tip_transport_t":"Transport",
        "tip_transport_d":"Walk, cycle, or carpool to cut emissions.",
        "tip_cta":       "💚 Let's build a Cleaner & Greener Tomorrow!",
        "tip_cta2":      "Every correct sort reduces landfill and fights climate change.",
        # Result card labels
        "lbl_detection": "AI Detection",
        "lbl_bin":       "Bin",
        "lbl_decomposes":"Decomposes",
        "lbl_ecoscore":  "Eco Score",
        "lbl_risk":      "Risk Level",
        "lbl_decomp":    "Decomposes",
        "lbl_predictions":"🤖 All Predictions",
        "lbl_impact":    "Environmental Impact",
        "lbl_disposal":  "Disposal Recommendation",
        "lbl_suggestion":"Eco Suggestion",
        "lbl_recycling": "Recycling Method",
        "btn_voice":     "🔊 Read Result Aloud",
        "lbl_conf":      "conf.",
        # Education tab
        "edu_title":     "🌍 Waste Category Guide",
        "edu_plastic_r": "Eco 35/100 - HIGH RISK",
        "edu_plastic_d": "Takes 400-1000 yrs. Blue bin. Rinse before recycling.",
        "edu_paper_r":   "Eco 75/100 - LOW RISK",
        "edu_paper_d":   "Biodegrades 2-6 weeks. Blue bin. Go digital.",
        "edu_glass_r":   "Eco 80/100 - LOW RISK",
        "edu_glass_d":   "100% recyclable. Sort by color. Green bin.",
        "edu_metal_r":   "Eco 70/100 - MODERATE RISK",
        "edu_metal_d":   "Saves 95% energy when recycled. Yellow bin.",
        "edu_card_r":    "Eco 72/100 - LOW RISK",
        "edu_card_d":    "Saves 17 trees per ton. Flatten. Blue bin.",
        "edu_trash_r":   "Eco 10/100 - HIGH RISK",
        "edu_trash_d":   "Produces methane. Bag securely. Black bin.",
        # About tab
        "about_title":   "ℹ️ About EcoSort AI",
        "about_mission_t":"🌍 Mission",
        "about_mission_d":"EcoSort AI helps individuals correctly sort waste, reducing landfill use, increasing recycling rates, and protecting our planet using AI.",
        "about_model_t": "🤖 AI Model",
        "about_model_d": "yangy50/garbage-classification\nHugging Face Transformers\nImage Classification Pipeline",
        "about_tech_t":  "⚙️ Tech Stack",
        "about_tech_d":  "Python • Gradio\nTransformers • PyTorch\nMatplotlib • Pillow",
        "about_lang_t":  "🌐 Languages",
        "about_lang_d":  "English\nTelugu (తెలుగు)\nHindi (हिंदी)",
        "about_voice_t": "🔊 Voice AI",
        "about_voice_d": "Browser Speech Synthesis\nTelugu & Hindi TTS\nAuto-reads AI results",
        # Footer
        "footer_quote":  '"The Earth does not belong to us — we belong to the Earth."',
        "footer_copy":   "© 2025 EcoSort AI — Smart Waste Segregation Assistant",
        # Recent scans
        "recent_scans":  "📋 Recent Scans",
        # Voice
        "voice_detected":"EcoSort AI detected",
        "voice_waste":   "waste with",
        "voice_conf":    "percent confidence. Eco score is",
        "voice_of":      "out of 100.",
        # No image
        "no_image_t":    "No image uploaded",
        "no_image_d":    "Please upload or capture an image first.",
        "no_scans":      "No scans yet.",
        "error_t":       "Analysis Error",
        "error_d":       "Please try a JPG/PNG/JPEG image.",
    },

    "te": {
        "header_sub":    "AI శక్తితో • పర్యావరణ కేంద్రీకృతం • భవిష్యత్తుకు సిద్ధం",
        "header_desc":   "తెలివైన వ్యర్థ నిర్వహణ ద్వారా స్వచ్ఛమైన భూమికి సహాయం.",
        "header_types":  "వ్యర్థ రకాలు",
        "header_langs":  "భాషలు",
        "header_powered":"AI శక్తి",
        "header_voice":  "వాయిస్ AI",
        "lang_label":    "🌐 భాష ఎంచుకోండి",
        "lang_hint":     "✨ భాష మారిస్తే మొత్తం ఇంటర్‌ఫేస్ మారుతుంది",
        "tab_scan":      "🔬 వ్యర్థం స్కాన్ చేయండి",
        "tab_analytics": "📊 విశ్లేషణలు",
        "tab_education": "🌱 పర్యావరణ విద్య",
        "tab_about":     "ℹ️ గురించి",
        "upload_label":  "📷 వ్యర్థం చిత్రాన్ని అప్‌లోడ్ చేయండి లేదా తీయండి",
        "tab_upload":    "📁 చిత్రం అప్‌లోడ్",
        "tab_webcam":    "📷 వెబ్‌క్యామ్",
        "img_drop":      "ఇక్కడ చిత్రాన్ని వదలండి లేదా అప్‌లోడ్ కోసం క్లిక్ చేయండి",
        "img_webcam":    "వెబ్‌క్యామ్ నుండి తీయండి",
        "btn_analyze":   "🔍 వ్యర్థాన్ని విశ్లేషించండి",
        "btn_clear":     "🗑️ తొలగించు",
        "result_label":  "🤖 AI విశ్లేషణ ఫలితం",
        "placeholder":   "చిత్రాన్ని అప్‌లోడ్ చేసి విశ్లేషించు నొక్కండి",
        "placeholder2":  "JPG • PNG • JPEG • వెబ్‌క్యామ్",
        "analytics_title":"📈 వ్యర్థ విశ్లేషణ డాష్‌బోర్డ్",
        "chart_donut":   "🍩 నమ్మకం విభజన",
        "chart_gauge":   "🌱 ఎకో స్కోర్ గేజ్",
        "chart_dist":    "📊 స్కాన్ పంపిణీ",
        "no_history":    "ఇంకా స్కాన్ చరిత్ర లేదు.",
        "tips_title":    "💚 పర్యావరణ విద్య మరియు చిట్కాలు",
        "tip_water_t":   "నీరు",
        "tip_water_d":   "బ్రష్ చేస్తున్నప్పుడు నల్లా మూయండి. లీకులు వెంటనే పరిష్కరించండి.",
        "tip_energy_t":  "శక్తి",
        "tip_energy_d":  "LED బల్బులకు మారండి. ఉపయోగించని పరికరాలను అన్‌ప్లగ్ చేయండి.",
        "tip_green_t":   "పర్యావరణం",
        "tip_green_d":   "చెట్లు నాటండి. వంట వ్యర్థాలను కంపోస్ట్ చేయండి.",
        "tip_transport_t":"రవాణా",
        "tip_transport_d":"నడవండి, సైకిల్ తొక్కండి లేదా కార్‌పూల్ చేయండి.",
        "tip_cta":       "💚 పరిశుభ్రమైన & పచ్చని రేపటిని నిర్మిద్దాం!",
        "tip_cta2":      "ప్రతి సరైన వ్యర్థ వేర్పాటు లాండ్‌ఫిల్‌ను తగ్గిస్తుంది.",
        "lbl_detection": "AI గుర్తింపు",
        "lbl_bin":       "డబ్బా",
        "lbl_decomposes":"కుళ్ళే సమయం",
        "lbl_ecoscore":  "ఎకో స్కోర్",
        "lbl_risk":      "ప్రమాద స్థాయి",
        "lbl_decomp":    "కుళ్ళే సమయం",
        "lbl_predictions":"🤖 అన్ని అంచనాలు",
        "lbl_impact":    "పర్యావరణ ప్రభావం",
        "lbl_disposal":  "పారవేత సిఫార్సు",
        "lbl_suggestion":"పర్యావరణ సూచన",
        "lbl_recycling": "రీసైక్లింగ్ పద్ధతి",
        "btn_voice":     "🔊 ఫలితాన్ని చదవండి",
        "lbl_conf":      "నమ్మకం",
        "edu_title":     "🌍 వ్యర్థ వర్గాల మార్గదర్శి",
        "edu_plastic_r": "ఎకో 35/100 - అధిక ప్రమాదం",
        "edu_plastic_d": "400-1000 సంవత్సరాలు పడుతుంది. నీలి డబ్బా. రీసైకిల్ కు ముందు కడగండి.",
        "edu_paper_r":   "ఎకో 75/100 - తక్కువ ప్రమాదం",
        "edu_paper_d":   "2-6 వారాల్లో కుళ్ళుతుంది. నీలి డబ్బా. డిజిటల్ వాడండి.",
        "edu_glass_r":   "ఎకో 80/100 - తక్కువ ప్రమాదం",
        "edu_glass_d":   "100% రీసైకిల్ అవుతుంది. రంగు ప్రకారం వేరు చేయండి. ఆకుపచ్చ డబ్బా.",
        "edu_metal_r":   "ఎకో 70/100 - మధ్యస్థ ప్రమాదం",
        "edu_metal_d":   "రీసైకిల్ చేస్తే 95% శక్తి ఆదా. పసుపు డబ్బా.",
        "edu_card_r":    "ఎకో 72/100 - తక్కువ ప్రమాదం",
        "edu_card_d":    "ఒక టన్‌కు 17 చెట్లు ఆదా. చదులు చేయండి. నీలి డబ్బా.",
        "edu_trash_r":   "ఎకో 10/100 - అధిక ప్రమాదం",
        "edu_trash_d":   "మీథేన్ ఉత్పత్తి చేస్తుంది. గట్టిగా బ్యాగ్ చేయండి. నల్ల డబ్బా.",
        "about_title":   "ℹ️ EcoSort AI గురించి",
        "about_mission_t":"🌍 లక్ష్యం",
        "about_mission_d":"EcoSort AI వ్యక్తులు వ్యర్థాలను సరిగ్గా వేరు చేయడంలో సహాయపడుతుంది, లాండ్‌ఫిల్ వినియోగాన్ని తగ్గిస్తుంది మరియు AI ఉపయోగించి మన గ్రహాన్ని రక్షిస్తుంది.",
        "about_model_t": "🤖 AI మోడల్",
        "about_model_d": "yangy50/garbage-classification\nHugging Face Transformers\nచిత్ర వర్గీకరణ పైప్‌లైన్",
        "about_tech_t":  "⚙️ టెక్ స్టాక్",
        "about_tech_d":  "Python • Gradio\nTransformers • PyTorch\nMatplotlib • Pillow",
        "about_lang_t":  "🌐 భాషలు",
        "about_lang_d":  "ఇంగ్లీష్\nతెలుగు\nహిందీ",
        "about_voice_t": "🔊 వాయిస్ AI",
        "about_voice_d": "బ్రౌజర్ స్పీచ్ సింథసిస్\nతెలుగు & హిందీ TTS\nAI ఫలితాలు స్వయంగా చదువుతుంది",
        "footer_quote":  '"భూమి మనది కాదు — మనం భూమికి చెందినవారం."',
        "footer_copy":   "© 2025 EcoSort AI — స్మార్ట్ వ్యర్థ వేర్పాటు సహాయకుడు",
        "recent_scans":  "📋 ఇటీవలి స్కాన్‌లు",
        "voice_detected":"EcoSort AI గుర్తించింది",
        "voice_waste":   "వ్యర్థాలు",
        "voice_conf":    "శాతం నమ్మకంతో. ఎకో స్కోర్",
        "voice_of":      "వంద లో.",
        "no_image_t":    "చిత్రం అప్‌లోడ్ కాలేదు",
        "no_image_d":    "దయచేసి ముందుగా చిత్రాన్ని అప్‌లోడ్ చేయండి.",
        "no_scans":      "ఇంకా స్కాన్‌లు లేవు.",
        "error_t":       "విశ్లేషణ లోపం",
        "error_d":       "దయచేసి JPG/PNG/JPEG చిత్రాన్ని ప్రయత్నించండి.",
    },

    "hi": {
        "header_sub":    "AI संचालित • पर्यावरण केंद्रित • भविष्य के लिए तैयार",
        "header_desc":   "स्मार्ट कचरा प्रबंधन से स्वच्छ पृथ्वी की ओर।",
        "header_types":  "कचरा प्रकार",
        "header_langs":  "भाषाएँ",
        "header_powered":"AI शक्ति",
        "header_voice":  "वॉयस AI",
        "lang_label":    "🌐 भाषा चुनें",
        "lang_hint":     "✨ भाषा बदलने पर पूरा इंटरफ़ेस बदल जाता है",
        "tab_scan":      "🔬 कचरा स्कैन करें",
        "tab_analytics": "📊 विश्लेषण",
        "tab_education": "🌱 पर्यावरण शिक्षा",
        "tab_about":     "ℹ️ के बारे में",
        "upload_label":  "📷 कचरे की तस्वीर अपलोड करें या लें",
        "tab_upload":    "📁 तस्वीर अपलोड",
        "tab_webcam":    "📷 वेबकैम",
        "img_drop":      "यहाँ तस्वीर छोड़ें या अपलोड के लिए क्लिक करें",
        "img_webcam":    "वेबकैम से तस्वीर लें",
        "btn_analyze":   "🔍 कचरे का विश्लेषण करें",
        "btn_clear":     "🗑️ साफ करें",
        "result_label":  "🤖 AI विश्लेषण परिणाम",
        "placeholder":   "तस्वीर अपलोड करें और विश्लेषण करें पर क्लिक करें",
        "placeholder2":  "JPG • PNG • JPEG • वेबकैम",
        "analytics_title":"📈 कचरा विश्लेषण डैशबोर्ड",
        "chart_donut":   "🍩 विश्वास विभाजन",
        "chart_gauge":   "🌱 इको स्कोर गेज",
        "chart_dist":    "📊 स्कैन वितरण",
        "no_history":    "अभी तक कोई स्कैन इतिहास नहीं।",
        "tips_title":    "💚 पर्यावरण शिक्षा और सुझाव",
        "tip_water_t":   "पानी",
        "tip_water_d":   "ब्रश करते समय नल बंद करें। रिसाव तुरंत ठीक करें।",
        "tip_energy_t":  "ऊर्जा",
        "tip_energy_d":  "LED बल्ब लगाएं। निष्क्रिय उपकरण अनप्लग करें।",
        "tip_green_t":   "हरित",
        "tip_green_d":   "पेड़ लगाएं। रसोई के कचरे को खाद बनाएं।",
        "tip_transport_t":"परिवहन",
        "tip_transport_d":"पैदल चलें, साइकिल चलाएं या कारपूल करें।",
        "tip_cta":       "💚 आइए एक स्वच्छ और हरा-भरा कल बनाएं!",
        "tip_cta2":      "हर सही छंटाई लैंडफिल कम करती है और जलवायु परिवर्तन से लड़ती है।",
        "lbl_detection": "AI पहचान",
        "lbl_bin":       "डिब्बा",
        "lbl_decomposes":"विघटन समय",
        "lbl_ecoscore":  "इको स्कोर",
        "lbl_risk":      "जोखिम स्तर",
        "lbl_decomp":    "विघटन समय",
        "lbl_predictions":"🤖 सभी अनुमान",
        "lbl_impact":    "पर्यावरणीय प्रभाव",
        "lbl_disposal":  "निपटान सिफारिश",
        "lbl_suggestion":"पर्यावरण सुझाव",
        "lbl_recycling": "पुनर्चक्रण विधि",
        "btn_voice":     "🔊 परिणाम पढ़ें",
        "lbl_conf":      "विश्वास",
        "edu_title":     "🌍 कचरा श्रेणी मार्गदर्शिका",
        "edu_plastic_r": "इको 35/100 - उच्च जोखिम",
        "edu_plastic_d": "400-1000 साल लगते हैं। नीला डिब्बा। रीसाइकिल से पहले धोएं।",
        "edu_paper_r":   "इको 75/100 - कम जोखिम",
        "edu_paper_d":   "2-6 हफ्तों में सड़ता है। नीला डिब्बा। डिजिटल अपनाएं।",
        "edu_glass_r":   "इको 80/100 - कम जोखिम",
        "edu_glass_d":   "100% रीसाइकिल। रंग के अनुसार छाँटें। हरा डिब्बा।",
        "edu_metal_r":   "इको 70/100 - मध्यम जोखिम",
        "edu_metal_d":   "रीसाइकिल करने पर 95% ऊर्जा बचत। पीला डिब्बा।",
        "edu_card_r":    "इको 72/100 - कम जोखिम",
        "edu_card_d":    "प्रति टन 17 पेड़ बचते हैं। चपटा करें। नीला डिब्बा।",
        "edu_trash_r":   "इको 10/100 - उच्च जोखिम",
        "edu_trash_d":   "मीथेन उत्पन्न करता है। कसकर बैग करें। काला डिब्बा।",
        "about_title":   "ℹ️ EcoSort AI के बारे में",
        "about_mission_t":"🌍 मिशन",
        "about_mission_d":"EcoSort AI लोगों को कचरे को सही तरीके से छाँटने में मदद करता है, लैंडफिल उपयोग कम करता है और AI से हमारे ग्रह की रक्षा करता है।",
        "about_model_t": "🤖 AI मॉडल",
        "about_model_d": "yangy50/garbage-classification\nHugging Face Transformers\nइमेज क्लासिफिकेशन पाइपलाइन",
        "about_tech_t":  "⚙️ टेक स्टैक",
        "about_tech_d":  "Python • Gradio\nTransformers • PyTorch\nMatplotlib • Pillow",
        "about_lang_t":  "🌐 भाषाएँ",
        "about_lang_d":  "अंग्रेज़ी\nतेलुगु\nहिंदी",
        "about_voice_t": "🔊 वॉयस AI",
        "about_voice_d": "ब्राउज़र स्पीच सिंथेसिस\nतेलुगु और हिंदी TTS\nAI परिणाम स्वतः पढ़ता है",
        "footer_quote":  '"पृथ्वी हमारी नहीं है — हम पृथ्वी के हैं।"',
        "footer_copy":   "© 2025 EcoSort AI — स्मार्ट कचरा पृथक्करण सहायक",
        "recent_scans":  "📋 हालिया स्कैन",
        "voice_detected":"EcoSort AI ने",
        "voice_waste":   "कचरे को",
        "voice_conf":    "प्रतिशत विश्वास के साथ पहचाना। इको स्कोर",
        "voice_of":      "है।",
        "no_image_t":    "कोई तस्वीर अपलोड नहीं हुई",
        "no_image_d":    "कृपया पहले एक तस्वीर अपलोड करें।",
        "no_scans":      "अभी तक कोई स्कैन नहीं।",
        "error_t":       "विश्लेषण त्रुटि",
        "error_d":       "कृपया JPG/PNG/JPEG तस्वीर आज़माएं।",
    },
}

# =============================================================
# WASTE DATABASE - content in all 3 languages
# =============================================================
WASTE_DB = {
    "plastic": {
        "eco_score": 35, "pollution_risk": {"en":"High","te":"అధిక","hi":"उच्च"},
        "risk_color": "#d96a6a",
        "en": {
            "impact":    "Plastic takes 400-1000 years to decompose. It pollutes oceans and harms marine life.",
            "disposal":  "Place in blue recycling bin. Rinse and remove caps. Never burn.",
            "suggestion":"Switch to reusable bags and bottles. Avoid single-use plastics.",
            "recycling": "Sort by resin code (1-7). PET (1) and HDPE (2) are most widely recycled.",
        },
        "te": {
            "impact":    "ప్లాస్టిక్ విఘటనమవడానికి 400-1000 సంవత్సరాలు పడుతుంది. సముద్రాలను కలుషితం చేస్తుంది.",
            "disposal":  "నీలి రీసైక్లింగ్ డబ్బాలో వేయండి. మూతలు తీసి కడగండి. ఎప్పుడూ కాల్చకండి.",
            "suggestion":"పునర్వినియోగ బ్యాగులు, సీసాలు వాడండి. సింగిల్-యూజ్ ప్లాస్టిక్ మానుకోండి.",
            "recycling": "రెజిన్ కోడ్ 1-7 ప్రకారం వేరు చేయండి. PET మరియు HDPE అత్యంత రీసైకిల్ అవుతాయి.",
        },
        "hi": {
            "impact":    "प्लास्टिक को सड़ने में 400-1000 साल लगते हैं। यह समुद्रों को प्रदूषित करता है।",
            "disposal":  "नीले रीसाइक्लिंग डिब्बे में डालें। ढक्कन हटाकर धोएं। कभी न जलाएं।",
            "suggestion":"पुनः उपयोग योग्य बैग और बोतलें उपयोग करें। सिंगल-यूज़ प्लास्टिक से बचें।",
            "recycling": "रेजिन कोड 1-7 के अनुसार छाँटें। PET और HDPE सबसे ज़्यादा रीसाइकिल होते हैं।",
        },
        "bin_color": {"en":"Blue Bin","te":"నీలి డబ్బా","hi":"नीला डिब्बा"},
        "decompose_years": {"en":"400-1000 yrs","te":"400-1000 సంవత్సరాలు","hi":"400-1000 साल"},
    },
    "paper": {
        "eco_score": 75, "pollution_risk": {"en":"Low","te":"తక్కువ","hi":"कम"},
        "risk_color": "#4caf82",
        "en": {
            "impact":    "Paper biodegrades in 2-6 weeks. Recycled paper uses 70% less energy.",
            "disposal":  "Flatten and place in paper bin. Keep dry. Remove plastic windows from envelopes.",
            "suggestion":"Go digital when possible. Choose FSC-certified paper products.",
            "recycling": "Clean paper in blue bin. Shredded paper in sealed bag or compost bin.",
        },
        "te": {
            "impact":    "కాగితం 2-6 వారాల్లో కుళ్ళిపోతుంది. రీసైకిల్డ్ కాగితం 70% శక్తి ఆదా చేస్తుంది.",
            "disposal":  "చదులుగా చేసి కాగితం డబ్బాలో వేయండి. తడిగా ఉంచకండి.",
            "suggestion":"సాధ్యమైనప్పుడు డిజిటల్‌కు వెళ్ళండి. FSC సర్టిఫైడ్ పేపర్ వాడండి.",
            "recycling": "శుభ్రమైన కాగితం నీలి డబ్బాలో. చిన్నగా చింపిన కాగితం కంపోస్ట్‌లో.",
        },
        "hi": {
            "impact":    "कागज़ 2-6 हफ्तों में सड़ जाता है। रीसाइक्लिंग से 70% ऊर्जा बचती है।",
            "disposal":  "चपटा करके कागज़ डिब्बे में डालें। सूखा रखें।",
            "suggestion":"जब संभव हो डिजिटल उपयोग करें। FSC प्रमाणित पेपर चुनें।",
            "recycling": "साफ़ कागज़ नीले डिब्बे में। कटा कागज़ कंपोस्ट में।",
        },
        "bin_color": {"en":"Blue Bin","te":"నీలి డబ్బా","hi":"नीला डिब्बा"},
        "decompose_years": {"en":"2-6 weeks","te":"2-6 వారాలు","hi":"2-6 हफ्ते"},
    },
    "glass": {
        "eco_score": 80, "pollution_risk": {"en":"Low","te":"తక్కువ","hi":"कम"},
        "risk_color": "#4caf82",
        "en": {
            "impact":    "Glass is infinitely recyclable without quality loss. Takes 1M+ years in landfill.",
            "disposal":  "Rinse and sort by color. Place in glass recycling bin or bottle bank.",
            "suggestion":"Prefer glass over plastic. Reuse jars. Return deposit bottles.",
            "recycling": "Sort by color: clear, green, brown. Drop at glass banks.",
        },
        "te": {
            "impact":    "గాజు నాణ్యత నష్టం లేకుండా అనంతంగా రీసైకిల్ చేయవచ్చు.",
            "disposal":  "కడిగి రంగు ప్రకారం వేరు చేయండి. గ్లాస్ రీసైక్లింగ్ డబ్బాలో వేయండి.",
            "suggestion":"ప్లాస్టిక్ కంటే గాజు ఇష్టపడండి. జాడీలు మళ్ళీ వాడండి.",
            "recycling": "రంగు ప్రకారం వేరు: తెల్లని, ఆకుపచ్చ, గోధుమ. గ్లాస్ బ్యాంక్‌లో వేయండి.",
        },
        "hi": {
            "impact":    "काँच को बिना गुणवत्ता खोए बार-बार रीसाइकिल किया जा सकता है।",
            "disposal":  "धोकर रंग के अनुसार अलग करें। ग्लास रीसाइक्लिंग डिब्बे में डालें।",
            "suggestion":"प्लास्टिक की जगह काँच पसंद करें। जार दोबारा इस्तेमाल करें।",
            "recycling": "रंग के अनुसार: साफ़, हरा, भूरा। ग्लास बैंक में डालें।",
        },
        "bin_color": {"en":"Green Bin","te":"ఆకుపచ్చ డబ్బా","hi":"हरा डिब्बा"},
        "decompose_years": {"en":"1M+ years","te":"10 లక్షల+ సంవత్సరాలు","hi":"10 लाख+ साल"},
    },
    "metal": {
        "eco_score": 70, "pollution_risk": {"en":"Moderate","te":"మధ్యస్థ","hi":"मध्यम"},
        "risk_color": "#c8922a",
        "en": {
            "impact":    "Recycling aluminum saves 95% of the energy to make new aluminum.",
            "disposal":  "Rinse and crush cans. Yellow/mixed recycling bin. Scrap yards for large items.",
            "suggestion":"Buy drinks in aluminum cans (100% recyclable). Donate scrap metal.",
            "recycling": "Aluminum, steel, tin go to curbside recycling. Large items to scrap yards.",
        },
        "te": {
            "impact":    "అల్యూమినియం రీసైక్లింగ్ కొత్త అల్యూమినియం తయారీకి అయ్యే 95% శక్తి ఆదా చేస్తుంది.",
            "disposal":  "కడిగి నలిపి పసుపు డబ్బాలో వేయండి. పెద్ద వస్తువులు స్క్రాప్ యార్డ్‌కు.",
            "suggestion":"అల్యూమినియం డబ్బాల్లో పానీయాలు కొనండి. స్క్రాప్ మెటల్ దానం చేయండి.",
            "recycling": "అల్యూమినియం, స్టీల్, టిన్ రీసైక్లింగ్‌కు. పెద్ద వస్తువులు స్క్రాప్ యార్డ్‌కు.",
        },
        "hi": {
            "impact":    "एल्यूमीनियम रीसाइक्लिंग से 95% ऊर्जा की बचत होती है।",
            "disposal":  "धोकर कुचलें और पीले डिब्बे में डालें। बड़े सामान स्क्रैप यार्ड में।",
            "suggestion":"एल्यूमीनियम के डिब्बों में पेय खरीदें। स्क्रैप मेटल दान करें।",
            "recycling": "एल्यूमीनियम, स्टील, टिन रीसाइक्लिंग में। बड़े सामान स्क्रैप यार्ड में।",
        },
        "bin_color": {"en":"Yellow Bin","te":"పసుపు డబ్బా","hi":"पीला डिब्बा"},
        "decompose_years": {"en":"50-200 yrs","te":"50-200 సంవత్సరాలు","hi":"50-200 साल"},
    },
    "cardboard": {
        "eco_score": 72, "pollution_risk": {"en":"Low","te":"తక్కువ","hi":"कम"},
        "risk_color": "#4caf82",
        "en": {
            "impact":    "Recycling one ton of cardboard saves 17 trees and 7000 gallons of water.",
            "disposal":  "Break down boxes flat. Keep dry. Remove tape. Place in paper/cardboard bin.",
            "suggestion":"Reuse boxes for storage. Compost small pieces.",
            "recycling": "Flat cardboard in blue bin. Wax-coated or wet cardboard to general waste.",
        },
        "te": {
            "impact":    "ఒక టన్ కార్డ్‌బోర్డ్ రీసైక్లింగ్ 17 చెట్లు మరియు 7000 గాలన్ల నీరు ఆదా చేస్తుంది.",
            "disposal":  "పెట్టెలు చదునుగా చేయండి. తడిగా ఉంచకండి. టేప్ తీయండి. కాగితం డబ్బాలో వేయండి.",
            "suggestion":"నిల్వ కోసం పెట్టెలు మళ్ళీ వాడండి. చిన్న ముక్కలు కంపోస్ట్ చేయండి.",
            "recycling": "సమతల కార్డ్‌బోర్డ్ నీలి డబ్బాలో. తడిసిన కార్డ్‌బోర్డ్ సాధారణ వ్యర్థంలో.",
        },
        "hi": {
            "impact":    "एक टन कार्डबोर्ड रीसाइक्लिंग से 17 पेड़ और 7000 गैलन पानी बचता है।",
            "disposal":  "बक्से चपटे करें। सूखा रखें। टेप हटाएं। कागज़ डिब्बे में डालें।",
            "suggestion":"भंडारण के लिए बक्से दोबारा उपयोग करें। छोटे टुकड़े खाद बनाएं।",
            "recycling": "सपाट कार्डबोर्ड नीले डिब्बे में। गीला कार्डबोर्ड सामान्य कचरे में।",
        },
        "bin_color": {"en":"Blue Bin","te":"నీలి డబ్బా","hi":"नीला डिब्बा"},
        "decompose_years": {"en":"2 months-1 yr","te":"2 నెలలు-1 సంవత్సరం","hi":"2 महीने-1 साल"},
    },
    "trash": {
        "eco_score": 10, "pollution_risk": {"en":"High","te":"అధిక","hi":"उच्च"},
        "risk_color": "#d96a6a",
        "en": {
            "impact":    "Landfill trash produces methane, which is 80x more potent than CO2 over 20 years.",
            "disposal":  "Bag securely and place in general waste bin. Separate recyclables first.",
            "suggestion":"Reduce, reuse, recycle before sending to landfill.",
            "recycling": "Most general trash cannot be recycled. Look for upcycling opportunities.",
        },
        "te": {
            "impact":    "లాండ్‌ఫిల్ వ్యర్థం మీథేన్ ఉత్పత్తి చేస్తుంది - CO2 కంటే 80 రెట్లు హానికరం.",
            "disposal":  "గట్టిగా బ్యాగ్ చేసి సాధారణ వ్యర్థ డబ్బాలో వేయండి. రీసైకిలేబుల్ వేరు చేయండి.",
            "suggestion":"లాండ్‌ఫిల్‌కు పంపే ముందు తగ్గించండి, పునర్వినియోగించండి, రీసైకిల్ చేయండి.",
            "recycling": "చాలా సాధారణ వ్యర్థం రీసైకిల్ కాదు. అప్‌సైక్లింగ్ అవకాశాలు చూడండి.",
        },
        "hi": {
            "impact":    "लैंडफिल कचरा मीथेन पैदा करता है जो CO2 से 80 गुना हानिकारक है।",
            "disposal":  "कसकर बैग करें और सामान्य कचरे के डिब्बे में डालें। रीसाइकिल योग्य अलग करें।",
            "suggestion":"लैंडफिल भेजने से पहले कम करें, पुनः उपयोग करें, रीसाइकिल करें।",
            "recycling": "अधिकांश सामान्य कचरा रीसाइकिल नहीं होता। अपसाइक्लिंग के अवसर देखें।",
        },
        "bin_color": {"en":"Black Bin","te":"నల్ల డబ్బా","hi":"काला डिब्बा"},
        "decompose_years": {"en":"Decades-centuries","te":"దశాబ్దాలు-శతాబ్దాలు","hi":"दशकों-सदियाँ"},
    },
}

ICON_EMOJI = {"plastic":"🧴","paper":"📄","glass":"🫙","metal":"🧲","cardboard":"📦","trash":"🗑"}
LABEL_MAP  = {
    "plastic":"plastic","paper":"paper","glass":"glass","metal":"metal",
    "cardboard":"cardboard","trash":"trash","garbage":"trash","biological":"trash",
    "brown-glass":"glass","green-glass":"glass","white-glass":"glass",
    "clothes":"trash","shoes":"trash","batteries":"metal","bottle":"plastic","bag":"plastic",
}

def detect_lang(s):
    s = s.strip().lower()
    if s.startswith("tel"): return "te"
    if s.startswith("hin"): return "hi"
    return "en"

print("Database loaded!")

# ----- Charts -----
BG="#090f0b"; BG2="#0c1610"; GREEN="#3abf8a"; DIM="#a8d4bc"; DARK="#16362a"

def _style(ax,fig):
    fig.patch.set_facecolor(BG); ax.set_facecolor(BG2)
    ax.tick_params(colors=DIM,labelsize=7)
    for sp in ax.spines.values(): sp.set_edgecolor(DARK)

def create_confidence_donut(predictions):
    labels=[p["label"].split("-")[0].capitalize() for p in predictions]
    sizes=[p["score"]*100 for p in predictions]
    colors=["#3abf8a","#1f8f62","#13744d","#0c5438","#073d27","#032216"]
    fig,ax=plt.subplots(figsize=(5,4),facecolor=BG); ax.set_facecolor(BG)
    _,texts,autotexts=ax.pie(sizes,labels=labels,colors=colors[:len(labels)],
        autopct="%1.1f%%",startangle=90,pctdistance=0.76,
        wedgeprops=dict(width=0.44,edgecolor=BG,linewidth=2))
    for t in texts: t.set_color(DIM); t.set_fontsize(8)
    for at in autotexts: at.set_color("#fff"); at.set_fontsize(7); at.set_fontweight("bold")
    ax.text(0,0.10,f"{sizes[0]:.1f}%",ha="center",va="center",fontsize=15,fontweight="bold",color=GREEN)
    ax.text(0,-0.18,labels[0],ha="center",va="center",fontsize=8,color=DIM)
    ax.set_title("AI Confidence Breakdown",color=GREEN,fontsize=10,fontweight="bold",pad=10)
    plt.tight_layout(); return fig

def create_eco_gauge(eco_score):
    fig,ax=plt.subplots(figsize=(5,3.5),facecolor=BG); ax.set_facecolor(BG)
    theta_bg=np.linspace(np.pi,0,300)
    ax.plot(np.cos(theta_bg),np.sin(theta_bg),linewidth=18,color="#142a1e",solid_capstyle="round")
    frac=max(0.01,eco_score/100); theta_f=np.linspace(np.pi,np.pi-frac*np.pi,300)
    arc_c=GREEN if eco_score>=70 else "#c8922a" if eco_score>=40 else "#d96a6a"
    ax.plot(np.cos(theta_f),np.sin(theta_f),linewidth=18,color=arc_c,solid_capstyle="round")
    ax.text(0,0.12,str(eco_score),ha="center",va="center",fontsize=30,fontweight="bold",color=arc_c)
    ax.text(0,-0.20,"/100",ha="center",va="center",fontsize=11,color=DIM)
    ax.text(0,-0.50,"ECO SCORE",ha="center",va="center",fontsize=8,color="#5a8a6a",fontweight="bold")
    ax.text(-1.05,-0.12,"0",ha="center",color="#304830",fontsize=7)
    ax.text(1.05,-0.12,"100",ha="center",color="#304830",fontsize=7)
    ax.set_xlim(-1.35,1.35); ax.set_ylim(-0.72,1.18); ax.axis("off")
    ax.set_title("Environmental Eco Score",color=GREEN,fontsize=10,fontweight="bold",pad=6)
    plt.tight_layout(); return fig

def create_waste_distribution(history):
    from collections import Counter
    if not history: labels,counts,bar_colors=["No data"],[1],["#142a1e"]
    else:
        ctr=Counter(h["waste_type"] for h in history)
        labels=[k.capitalize() for k in ctr]; counts=list(ctr.values())
        pal=["#3abf8a","#1f8f62","#13744d","#0c5438","#073d27","#032216"]
        bar_colors=pal[:len(labels)]
    fig,ax=plt.subplots(figsize=(6,3.5),facecolor=BG); _style(ax,fig)
    bars=ax.bar(labels,counts,color=bar_colors,edgecolor=BG,linewidth=1.5,width=0.5)
    for bar,cnt in zip(bars,counts):
        if labels[0]!="No data":
            ax.text(bar.get_x()+bar.get_width()/2,bar.get_height()+0.04,str(cnt),
                    ha="center",va="bottom",color=DIM,fontsize=8,fontweight="bold")
    ax.set_title("Scan History Distribution",color=GREEN,fontsize=10,fontweight="bold",pad=8)
    ax.set_ylabel("Count",color=DIM,fontsize=8)
    ax.yaxis.set_major_locator(ticker.MaxNLocator(integer=True))
    ax.grid(axis="y",color=DARK,linewidth=0.5,alpha=0.7)
    for sp in ["top","right"]: ax.spines[sp].set_visible(False)
    plt.tight_layout(); return fig

print("Charts ready!")

# =============================================================
# ANALYSIS FUNCTION
# =============================================================
def analyze_waste(image, language):
    global scan_history
    lc = detect_lang(language)
    u  = UI[lc]

    if image is None:
        err = (
            f'<div style="color:#d96a6a;padding:30px;text-align:center;'
            f'border:1px solid #d96a6a33;border-radius:14px">'
            f'<div style="font-size:38px;margin-bottom:8px">⚠️</div>'
            f'<div style="font-size:14px;font-weight:bold">{u["no_image_t"]}</div>'
            f'<div style="color:#8aaa98;font-size:12px;margin-top:6px">{u["no_image_d"]}</div></div>'
        )
        return (err, None, None, None,
                f'<p style="color:#304830;padding:10px">{u["no_scans"]}</p>')

    try:
        if not isinstance(image, Image.Image): image = Image.fromarray(image)
        if image.mode != "RGB": image = image.convert("RGB")

        results   = classifier(image)
        top       = results[0]
        raw       = top["label"].lower().replace(" ","-")
        waste_key = "trash"
        for k,v in LABEL_MAP.items():
            if k in raw: waste_key=v; break

        confidence = top["score"]*100
        info       = WASTE_DB[waste_key]
        content    = info[lc]

        impact_text   = content["impact"]
        disposal_text = content["disposal"]
        suggest_text  = content["suggestion"]
        recycling_txt = content["recycling"]

        eco_score    = min(100, max(5, int(info["eco_score"]*(0.80+0.20*top["score"]))))
        risk_color   = info["risk_color"]
        pollution_risk = info["pollution_risk"][lc]
        bin_color    = info["bin_color"][lc]
        decompose_yrs= info["decompose_years"][lc]

        conf_color = GREEN if confidence>=75 else "#c8922a" if confidence>=50 else "#d96a6a"
        eco_color  = GREEN if eco_score>=70  else "#c8922a" if eco_score>=40  else "#d96a6a"
        risk_pct   = 88 if "igh" in pollution_risk or "అధిక" in pollution_risk or "उच्च" in pollution_risk \
                     else 28 if "ow" in pollution_risk or "తక్కువ" in pollution_risk or "कम" in pollution_risk \
                     else 58
        icon = ICON_EMOJI.get(waste_key,"🗑")

        pred_rows=""
        for r in results[:5]:
            pl=r["label"].split("-")[0].capitalize(); ps=r["score"]*100; pw=max(2,int(ps))
            pred_rows+=(
                f'<div style="margin:6px 0">'
                f'<div style="display:flex;justify-content:space-between;margin-bottom:3px">'
                f'<span style="color:#a8d4bc;font-size:11px">{pl}</span>'
                f'<span style="color:#3abf8a;font-size:11px;font-weight:bold">{ps:.1f}%</span></div>'
                f'<div style="background:#0f2a1c;border-radius:3px;height:5px;overflow:hidden">'
                f'<div style="width:{pw}%;height:100%;'
                f'background:linear-gradient(90deg,#13744d,#3abf8a);border-radius:3px"></div>'
                f'</div></div>'
            )

        r_val=36; circ=2*3.14159*r_val; dash=(confidence/100)*circ

        # Voice text in selected language
        if lc=="te":
            voice_text=(f"EcoSort AI {waste_key} వ్యర్థాలను {confidence:.0f} శాతం నమ్మకంతో గుర్తించింది. "
                        f"ఎకో స్కోర్ {eco_score}. {disposal_text}")
            tts_lang="te-IN"
        elif lc=="hi":
            voice_text=(f"EcoSort AI ने {waste_key} कचरे को {confidence:.0f} प्रतिशत विश्वास के साथ पहचाना। "
                        f"इको स्कोर {eco_score} है। {disposal_text}")
            tts_lang="hi-IN"
        else:
            voice_text=(f"EcoSort AI detected {waste_key} waste with {confidence:.0f} percent confidence. "
                        f"Eco score is {eco_score} out of 100. {disposal_text}")
            tts_lang="en-US"

        def js_str(s):
            return s.replace("\\","\\\\").replace('"','\\"').replace("'","\\'").replace("\n"," ").replace("\r"," ")
        v_safe=js_str(voice_text)

        js_btn=(
            "(function(){"
              "var S=window.speechSynthesis||(window.parent&&window.parent.speechSynthesis)||null;"
              "if(!S){alert('Speech not supported. Try Chrome or Edge.');return;}"
              "S.cancel();"
              "var u=new SpeechSynthesisUtterance();"
              f"u.text='{v_safe}';"
              f"u.lang='{tts_lang}';"
              "u.rate=0.88;u.pitch=1.05;u.volume=1.0;"
              "var vs=S.getVoices();"
              f"var lc='{lc}';"
              "var m=vs.find(function(v){return v.lang.toLowerCase().startsWith(lc);});"
              "if(m)u.voice=m;"
              "S.speak(u);"
            "})()"
        )
        js_auto=(
            "<script>(function(){"
              "var S=window.speechSynthesis||(window.parent&&window.parent.speechSynthesis)||null;"
              "if(!S)return; S.cancel();"
              "var u=new SpeechSynthesisUtterance();"
              f"u.text='{v_safe}';"
              f"u.lang='{tts_lang}';"
              "u.rate=0.88;u.pitch=1.05;u.volume=1.0;"
              f"var lc='{lc}';"
              "function doSpeak(){"
                "var vs=S.getVoices();"
                "var m=vs.find(function(v){return v.lang.toLowerCase().startsWith(lc);});"
                "if(m)u.voice=m; S.speak(u);}"
              "var vs=S.getVoices();"
              "if(vs.length>0){setTimeout(doSpeak,700);}"
              "else{S.onvoiceschanged=function(){setTimeout(doSpeak,300);}; }"
            "})();</script>"
        )

        lbl = u  # shortcut

        result_html = f"""
<style>
@keyframes fadeUp{{from{{opacity:0;transform:translateY(10px)}}to{{opacity:1;transform:translateY(0)}}}}
@keyframes glow{{0%,100%{{box-shadow:0 0 6px #3abf8a14}}50%{{box-shadow:0 0 16px #3abf8a38}}}}
.ec{{background:rgba(0,22,12,.90);border:1px solid rgba(58,191,138,.15);border-radius:14px;
     padding:14px;margin:8px 0;animation:fadeUp .35s ease;transition:border-color .3s}}
.ec:hover{{border-color:rgba(58,191,138,.36);animation:glow 2s infinite}}
.elbl{{color:#3abf8a;font-size:9px;text-transform:uppercase;font-weight:bold;margin-bottom:4px;letter-spacing:1.3px}}
.etxt{{color:#96bba8;font-size:12px;line-height:1.65}}
.mgrid{{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin:10px 0}}
.mc{{background:rgba(0,14,8,.94);border:1px solid rgba(58,191,138,.11);border-radius:11px;padding:12px;text-align:center;transition:.25s}}
.mc:hover{{border-color:rgba(58,191,138,.32);transform:translateY(-2px)}}
.igrid{{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:10px}}
@media(max-width:560px){{.mgrid{{grid-template-columns:1fr 1fr}}.igrid{{grid-template-columns:1fr}}}}
</style>
<div class="ec" style="text-align:center;border-color:rgba(58,191,138,.25)">
  <div style="font-size:44px;margin-bottom:5px">{icon}</div>
  <div style="color:#5a8a6a;font-size:9px;text-transform:uppercase;letter-spacing:2px;margin-bottom:3px">{lbl["lbl_detection"]}</div>
  <div style="color:#3abf8a;font-size:26px;font-weight:900;margin:3px 0">{waste_key.upper()}</div>
  <svg width="90" height="90" viewBox="0 0 90 90" style="margin:6px auto;display:block">
    <circle cx="45" cy="45" r="{r_val}" fill="none" stroke="#0f2a1c" stroke-width="9"/>
    <circle cx="45" cy="45" r="{r_val}" fill="none" stroke="{conf_color}" stroke-width="9"
      stroke-dasharray="{dash:.2f} {circ:.2f}" stroke-dashoffset="{circ/4:.2f}"
      stroke-linecap="round" style="filter:drop-shadow(0 0 5px {conf_color}88)"/>
    <text x="45" y="42" text-anchor="middle" fill="{conf_color}" font-size="14" font-weight="bold" font-family="monospace">{confidence:.0f}%</text>
    <text x="45" y="55" text-anchor="middle" fill="#304830" font-size="8" font-family="monospace">{lbl["lbl_conf"]}</text>
  </svg>
  <div style="color:#4a7a5a;font-size:11px">
    {lbl["lbl_bin"]}: <b style="color:#d4edd8">{bin_color}</b>&nbsp;&bull;&nbsp;
    {lbl["lbl_decomposes"]}: <b style="color:#d4edd8">{decompose_yrs}</b>
  </div>
</div>
<div class="mgrid">
  <div class="mc">
    <div style="font-size:20px;margin-bottom:4px">🌱</div>
    <div style="color:#3abf8a;font-size:9px;text-transform:uppercase;font-weight:bold">{lbl["lbl_ecoscore"]}</div>
    <div style="color:{eco_color};font-size:22px;font-weight:900">{eco_score}</div>
    <div style="color:#304830;font-size:9px">/100</div>
    <div style="background:#0f2a1c;border-radius:3px;height:4px;margin-top:7px;overflow:hidden">
      <div style="width:{eco_score}%;height:100%;background:{eco_color};border-radius:3px"></div>
    </div>
  </div>
  <div class="mc">
    <div style="font-size:20px;margin-bottom:4px">⚠️</div>
    <div style="color:#3abf8a;font-size:9px;text-transform:uppercase;font-weight:bold">{lbl["lbl_risk"]}</div>
    <div style="color:{risk_color};font-size:14px;font-weight:bold">{pollution_risk}</div>
    <div style="background:#0f2a1c;border-radius:3px;height:4px;margin-top:7px;overflow:hidden">
      <div style="width:{risk_pct}%;height:100%;background:{risk_color};border-radius:3px"></div>
    </div>
  </div>
  <div class="mc">
    <div style="font-size:20px;margin-bottom:4px">⏳</div>
    <div style="color:#3abf8a;font-size:9px;text-transform:uppercase;font-weight:bold">{lbl["lbl_decomp"]}</div>
    <div style="color:#c8922a;font-size:10px;font-weight:bold;margin-top:5px;line-height:1.3">{decompose_yrs}</div>
  </div>
</div>
<div class="ec">
  <div class="elbl">{lbl["lbl_predictions"]}</div>
  {pred_rows}
</div>
<div class="igrid">
  <div class="ec"><div style="font-size:22px;margin-bottom:5px">🌍</div>
    <div class="elbl">{lbl["lbl_impact"]}</div><div class="etxt">{impact_text}</div></div>
  <div class="ec"><div style="font-size:22px;margin-bottom:5px">🗂️</div>
    <div class="elbl">{lbl["lbl_disposal"]}</div><div class="etxt">{disposal_text}</div></div>
  <div class="ec"><div style="font-size:22px;margin-bottom:5px">💡</div>
    <div class="elbl">{lbl["lbl_suggestion"]}</div><div class="etxt">{suggest_text}</div></div>
  <div class="ec"><div style="font-size:22px;margin-bottom:5px">♻️</div>
    <div class="elbl">{lbl["lbl_recycling"]}</div><div class="etxt">{recycling_txt}</div></div>
</div>
<div style="text-align:center;margin-top:14px">
  <button onclick="{js_btn}"
    style="background:linear-gradient(135deg,#0a4f30,#156644);color:#b8e8cc;
           border:1px solid #3abf8a44;border-radius:10px;padding:11px 30px;
           font-size:13px;font-weight:bold;cursor:pointer;letter-spacing:0.8px;
           transition:all .2s;font-family:inherit">
    {lbl["btn_voice"]}
  </button>
</div>
{js_auto}
"""

        scan_history.append({"waste_type":waste_key,"confidence":confidence,
                              "eco_score":eco_score,"timestamp":datetime.now().strftime("%H:%M:%S"),"icon":icon})
        scan_history=scan_history[-20:]

        hist_rows=""
        for h in reversed(scan_history[-8:]):
            hc=GREEN if h["confidence"]>=75 else "#c8922a" if h["confidence"]>=50 else "#d96a6a"
            hist_rows+=(
                f'<div style="display:flex;align-items:center;justify-content:space-between;'
                f'padding:8px 14px;border-bottom:1px solid #0f2a1c">'
                f'<span style="font-size:18px">{h["icon"]}</span>'
                f'<span style="color:#a8d4bc;font-size:12px;font-weight:bold;flex:1;padding-left:10px">'
                f'{h["waste_type"].capitalize()}</span>'
                f'<span style="color:{hc};font-size:11px;font-weight:bold">{h["confidence"]:.0f}%</span>'
                f'<span style="color:#304830;font-size:10px;padding-left:10px">{h["timestamp"]}</span></div>'
            )
        history_html=(
            '<div style="background:rgba(0,14,8,.94);border:1px solid rgba(58,191,138,0.12);border-radius:12px;overflow:hidden">'
            f'<div style="background:#000e06;padding:9px 14px;border-bottom:1px solid #0f2a1c">'
            f'<span style="color:#3abf8a;font-size:9px;text-transform:uppercase;font-weight:bold;letter-spacing:1.5px">{u["recent_scans"]}</span></div>'
            +(hist_rows if hist_rows else f'<p style="color:#304830;padding:14px;font-size:12px">{u["no_scans"]}</p>')
            +'</div>'
        )

        return result_html, create_confidence_donut(results), create_eco_gauge(eco_score), \
               create_waste_distribution(scan_history), history_html

    except Exception as e:
        import traceback; traceback.print_exc()
        u2=UI[detect_lang(language)]
        error_html=(
            f'<div style="background:rgba(40,0,0,.88);border:1px solid #d96a6a33;border-radius:14px;padding:24px;text-align:center">'
            f'<div style="font-size:36px;margin-bottom:8px">❌</div>'
            f'<div style="color:#d96a6a;font-size:14px;font-weight:bold">{u2["error_t"]}</div>'
            f'<div style="color:#ffaaaa;font-size:12px;margin-top:6px">{str(e)[:200]}</div>'
            f'<div style="color:#666;font-size:11px;margin-top:8px">{u2["error_d"]}</div></div>'
        )
        return (error_html,None,None,None,f'<p style="color:#d96a6a;padding:10px">Error.</p>')

print("Analysis function ready!")

# =============================================================
# CSS
# =============================================================
CSS="""
*,*::before,*::after{box-sizing:border-box}
body,.gradio-container{background:#060f09!important;color:#c8e0cc!important;
  font-family:"Share Tech Mono","Courier New",monospace!important}
::-webkit-scrollbar{width:5px}
::-webkit-scrollbar-track{background:#060f09}
::-webkit-scrollbar-thumb{background:#163a26;border-radius:3px}
.gradio-container .gr-panel,.gradio-container .gr-box{
  background:rgba(0,255,100,0.018)!important;border:1px solid rgba(58,191,138,0.13)!important;border-radius:15px!important}
.gradio-container label,.gradio-container .label-wrap span{
  color:#3abf8a!important;font-size:9px!important;text-transform:uppercase;letter-spacing:1.6px;font-weight:bold}
.gradio-container button.primary,.gradio-container button[variant="primary"]{
  background:linear-gradient(135deg,#0a4f30,#156644)!important;color:#b8e8cc!important;
  border:1px solid #3abf8a38!important;border-radius:10px!important;font-weight:bold!important;
  font-size:11px!important;text-transform:uppercase;box-shadow:0 2px 10px rgba(58,191,138,0.10)!important;transition:all .2s!important}
.gradio-container button.primary:hover{
  background:linear-gradient(135deg,#0e6640,#1d8a58)!important;
  box-shadow:0 0 16px rgba(58,191,138,0.25)!important;transform:translateY(-1px)!important}
.gradio-container button.secondary,.gradio-container button[variant="secondary"]{
  background:transparent!important;color:#3abf8a!important;
  border:1px solid rgba(58,191,138,0.22)!important;border-radius:10px!important}
.gradio-container .gr-image,.gradio-container .image-container,
.gradio-container [data-testid="image"],.gradio-container .upload-container,
.gradio-container .image-frame,.gradio-container div[class*="image"],
.gradio-container div[class*="upload"],.gradio-container canvas{
  background:rgba(0,16,8,0.75)!important;background-color:rgba(0,16,8,0.75)!important}
.gradio-container .gr-file-upload,.gradio-container .gr-file-upload>div{
  background:rgba(0,16,8,0.60)!important;border:2px dashed rgba(58,191,138,0.22)!important;border-radius:13px!important}
.gradio-container .tab-nav button{
  background:transparent!important;color:#304830!important;border-bottom:2px solid transparent!important;
  border-radius:0!important;box-shadow:none!important;font-size:10px!important;
  text-transform:uppercase;letter-spacing:1px;transition:color .2s!important}
.gradio-container .tab-nav button.selected{color:#3abf8a!important;border-bottom-color:#3abf8a!important}
.gradio-container .tab-nav button:hover{color:#5abf90!important}
.gradio-container select,.gradio-container .gr-dropdown,.gradio-container input[type="text"]{
  background:#090f0b!important;background-color:#090f0b!important;
  color:#c8e0cc!important;border:1px solid rgba(58,191,138,0.20)!important;border-radius:8px!important}
.gradio-container img{border-radius:10px!important;border:1px solid rgba(58,191,138,0.14)!important}
@keyframes wv{0%,100%{height:4px}50%{height:16px}}
.wvb{display:inline-block;width:3px;background:#3abf8a;border-radius:2px;margin:0 2px;animation:wv 1.2s ease-in-out infinite}
.wvb:nth-child(2){animation-delay:.15s}.wvb:nth-child(3){animation-delay:.30s}
.wvb:nth-child(4){animation-delay:.45s}.wvb:nth-child(5){animation-delay:.60s}
"""

# =============================================================
# UI BUILDER - rebuilds entire interface in chosen language
# =============================================================
def build_interface(language):
    lc = detect_lang(language)
    u  = UI[lc]

    def placeholder_html():
        return (f'<div style="text-align:center;padding:44px 20px;color:#163a26;'
                f'border:2px dashed #163a26;border-radius:14px">'
                f'<div style="font-size:46px;margin-bottom:10px">🌱</div>'
                f'<div style="font-size:13px">{u["placeholder"]}</div>'
                f'<div style="font-size:10px;margin-top:5px;color:#0f2a1c">{u["placeholder2"]}</div></div>')

    def header_html():
        return (f'<div style="background:linear-gradient(135deg,#020d06,#051a0d 60%,#091f10);'
                f'border:1px solid rgba(58,191,138,0.16);border-radius:18px;'
                f'padding:28px 20px 22px;text-align:center;position:relative;overflow:hidden;margin-bottom:6px">'
                f'<div style="position:relative;z-index:1">'
                f'<div style="font-size:46px;margin-bottom:6px">🌍</div>'
                f'<h1 style="color:#3abf8a;font-size:clamp(18px,3.2vw,30px);font-weight:900;'
                f'letter-spacing:4px;text-transform:uppercase;margin:0;'
                f'text-shadow:0 0 22px rgba(58,191,138,0.32)">EcoSort AI</h1>'
                f'<div style="color:rgba(58,191,138,0.42);font-size:10px;letter-spacing:4px;'
                f'text-transform:uppercase;margin:5px 0 11px">{u["header_sub"]}</div>'
                f'<div style="color:#6a9a7a;font-size:12px;max-width:460px;margin:0 auto 14px;line-height:1.5">'
                f'{u["header_desc"]}</div>'
                f'<div style="display:flex;justify-content:center;gap:24px;flex-wrap:wrap">'
                f'<div style="text-align:center"><div style="color:#3abf8a;font-size:16px;font-weight:bold">6</div>'
                f'<div style="color:#304830;font-size:8px;text-transform:uppercase;letter-spacing:1px">{u["header_types"]}</div></div>'
                f'<div style="text-align:center"><div style="color:#3abf8a;font-size:16px;font-weight:bold">3</div>'
                f'<div style="color:#304830;font-size:8px;text-transform:uppercase;letter-spacing:1px">{u["header_langs"]}</div></div>'
                f'<div style="text-align:center"><div style="color:#3abf8a;font-size:16px;font-weight:bold">AI</div>'
                f'<div style="color:#304830;font-size:8px;text-transform:uppercase;letter-spacing:1px">{u["header_powered"]}</div></div>'
                f'<div style="text-align:center"><div style="color:#3abf8a;font-size:16px;font-weight:bold">🔊</div>'
                f'<div style="color:#304830;font-size:8px;text-transform:uppercase;letter-spacing:1px">{u["header_voice"]}</div></div>'
                f'</div></div></div>')

    def footer_html():
        return (f'<div style="background:rgba(58,191,138,0.02);border-top:1px solid rgba(58,191,138,0.09);'
                f'border-radius:12px;padding:14px;text-align:center;margin-top:10px">'
                f'<div style="margin-bottom:8px;display:flex;align-items:center;justify-content:center;gap:3px">'
                f'<span style="color:#304830;font-size:9px;margin-right:6px">🔊 {u["header_voice"]}</span>'
                f'<div class="wvb"></div><div class="wvb"></div><div class="wvb"></div>'
                f'<div class="wvb"></div><div class="wvb"></div></div>'
                f'<div style="color:#2a7a50;font-size:11px;font-style:italic;margin-bottom:5px">{u["footer_quote"]}</div>'
                f'<div style="color:#1a3a22;font-size:10px">🌐 {u["footer_copy"]}</div></div>')

    def tips_html():
        return (f'<div style="background:rgba(0,14,8,0.92);border:1px solid rgba(58,191,138,0.11);'
                f'border-radius:13px;padding:14px;margin-top:12px">'
                f'<div style="color:#3abf8a;font-size:9px;text-transform:uppercase;'
                f'letter-spacing:1.5px;font-weight:bold;margin-bottom:12px">{u["tips_title"]}</div>'
                f'<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px">'
                f'<div style="background:rgba(58,191,138,0.03);border-radius:9px;padding:10px;border:1px solid rgba(58,191,138,0.08)">'
                f'<div style="font-size:17px;margin-bottom:3px">🚰</div>'
                f'<div style="color:#3abf8a;font-size:8px;text-transform:uppercase;font-weight:bold">{u["tip_water_t"]}</div>'
                f'<div style="color:#6a9a7a;font-size:10px;margin-top:3px;line-height:1.5">{u["tip_water_d"]}</div></div>'
                f'<div style="background:rgba(58,191,138,0.03);border-radius:9px;padding:10px;border:1px solid rgba(58,191,138,0.08)">'
                f'<div style="font-size:17px;margin-bottom:3px">⚡</div>'
                f'<div style="color:#3abf8a;font-size:8px;text-transform:uppercase;font-weight:bold">{u["tip_energy_t"]}</div>'
                f'<div style="color:#6a9a7a;font-size:10px;margin-top:3px;line-height:1.5">{u["tip_energy_d"]}</div></div>'
                f'<div style="background:rgba(58,191,138,0.03);border-radius:9px;padding:10px;border:1px solid rgba(58,191,138,0.08)">'
                f'<div style="font-size:17px;margin-bottom:3px">🌱</div>'
                f'<div style="color:#3abf8a;font-size:8px;text-transform:uppercase;font-weight:bold">{u["tip_green_t"]}</div>'
                f'<div style="color:#6a9a7a;font-size:10px;margin-top:3px;line-height:1.5">{u["tip_green_d"]}</div></div>'
                f'<div style="background:rgba(58,191,138,0.03);border-radius:9px;padding:10px;border:1px solid rgba(58,191,138,0.08)">'
                f'<div style="font-size:17px;margin-bottom:3px">🚲</div>'
                f'<div style="color:#3abf8a;font-size:8px;text-transform:uppercase;font-weight:bold">{u["tip_transport_t"]}</div>'
                f'<div style="color:#6a9a7a;font-size:10px;margin-top:3px;line-height:1.5">{u["tip_transport_d"]}</div></div>'
                f'</div>'
                f'<div style="margin-top:11px;padding:10px;background:rgba(58,191,138,0.04);'
                f'border-radius:9px;border-left:3px solid #3abf8a40">'
                f'<div style="color:#3abf8a;font-size:11px;font-weight:bold">{u["tip_cta"]}</div>'
                f'<div style="color:#6a9a7a;font-size:11px;margin-top:3px">{u["tip_cta2"]}</div>'
                f'</div></div>')

    def education_html():
        return (f'<div>'
                f'<div style="color:#3abf8a;font-size:9px;text-transform:uppercase;'
                f'letter-spacing:1.8px;font-weight:bold;margin-bottom:14px">{u["edu_title"]}</div>'
                f'<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:11px">'
                +"\n".join([
                    f'<div style="background:rgba(0,22,12,.90);border:1px solid rgba(58,191,138,.14);border-radius:13px;padding:15px">'
                    f'<div style="font-size:24px;margin-bottom:5px">{ico} {name}</div>'
                    f'<div style="color:#3abf8a;font-size:8px;text-transform:uppercase;font-weight:bold;margin-bottom:4px">{risk}</div>'
                    f'<div style="color:#6a9a7a;font-size:11px;line-height:1.6">{desc}</div></div>'
                    for ico,name,risk,desc in [
                        ("🧴","Plastic",u["edu_plastic_r"],u["edu_plastic_d"]),
                        ("📄","Paper",  u["edu_paper_r"],  u["edu_paper_d"]),
                        ("🫙","Glass",  u["edu_glass_r"],  u["edu_glass_d"]),
                        ("🧲","Metal",  u["edu_metal_r"],  u["edu_metal_d"]),
                        ("📦","Cardboard",u["edu_card_r"], u["edu_card_d"]),
                        ("🗑️","Trash",  u["edu_trash_r"],  u["edu_trash_d"]),
                    ]
                ])
                +f'</div></div>')

    def about_html():
        rows=[(u["about_model_t"],u["about_model_d"]),(u["about_tech_t"],u["about_tech_d"]),
              (u["about_lang_t"],u["about_lang_d"]),(u["about_voice_t"],u["about_voice_d"])]
        cards="".join(
            f'<div style="background:rgba(0,14,8,.94);border:1px solid rgba(58,191,138,.11);border-radius:11px;padding:14px">'
            f'<div style="color:#3abf8a;font-size:10px;font-weight:bold;margin-bottom:6px">{t}</div>'
            f'<div style="color:#6a9a7a;font-size:11px;line-height:1.6">{d.replace(chr(10),"<br>")}</div></div>'
            for t,d in rows)
        return (f'<div style="max-width:620px">'
                f'<div style="color:#3abf8a;font-size:9px;text-transform:uppercase;'
                f'letter-spacing:1.8px;font-weight:bold;margin-bottom:14px">{u["about_title"]}</div>'
                f'<div style="background:rgba(0,22,12,.90);border:1px solid rgba(58,191,138,.14);'
                f'border-radius:13px;padding:18px;margin-bottom:12px">'
                f'<div style="color:#3abf8a;font-size:13px;font-weight:bold;margin-bottom:8px">{u["about_mission_t"]}</div>'
                f'<div style="color:#6a9a7a;font-size:12px;line-height:1.7">{u["about_mission_d"]}</div></div>'
                f'<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px">{cards}</div></div>')

    return placeholder_html, header_html, footer_html, tips_html, education_html, about_html, u

# =============================================================
# GRADIO UI
# =============================================================
LANG_CHOICES = ["English", "Telugu", "Hindi"]

with gr.Blocks(css=CSS, title="🌍 EcoSort AI",
    theme=gr.themes.Base(
        primary_hue="emerald", secondary_hue="green", neutral_hue="slate",
        font=[gr.themes.GoogleFont("Share Tech Mono"),"Courier New","monospace"],
    ).set(body_background_fill="#060f09",
          block_background_fill="rgba(58,191,138,0.018)",
          block_border_color="rgba(58,191,138,0.12)",
          button_primary_background_fill="linear-gradient(135deg,#0a4f30,#156644)",
          button_primary_text_color="#b8e8cc")
) as demo:

    # ---- dynamic HTML blocks (update on lang change) ----
    header_block  = gr.HTML()
    lang_hint_box = gr.HTML()

    with gr.Row():
        language_dd = gr.Dropdown(choices=LANG_CHOICES, value="English",
                                  label="🌐 Select Language / భాష / भाषा", scale=2)

    with gr.Tabs() as tabs:

        with gr.TabItem("🔬 SCAN WASTE", id="scan") as tab_scan:
            with gr.Row():
                with gr.Column(scale=1):
                    upload_lbl  = gr.HTML()
                    with gr.Tabs():
                        with gr.TabItem("📁 Upload Image") as ti_upload:
                            upload_img = gr.Image(type="pil", sources=["upload","clipboard"], height=250)
                        with gr.TabItem("📷 Webcam") as ti_webcam:
                            webcam_img = gr.Image(type="pil", sources=["webcam"], height=250)
                    scan_btn  = gr.Button("🔍 Analyze Waste Now", variant="primary",  size="lg")
                    clear_btn = gr.Button("🗑️ Clear",             variant="secondary", size="sm")
                    tips_block = gr.HTML()

                with gr.Column(scale=1):
                    result_lbl     = gr.HTML()
                    result_display = gr.HTML()

        with gr.TabItem("📊 ANALYTICS", id="analytics") as tab_analytics:
            analytics_lbl = gr.HTML()
            with gr.Row():
                donut_chart = gr.Plot()
                gauge_chart = gr.Plot()
            dist_chart      = gr.Plot()
            history_display = gr.HTML()

        with gr.TabItem("🌱 ECO EDUCATION", id="education") as tab_edu:
            education_block = gr.HTML()

        with gr.TabItem("ℹ️ ABOUT", id="about") as tab_about:
            about_block = gr.HTML()

    footer_block = gr.HTML()

    # ==========================================================
    # Helper: rebuild all UI strings when language changes
    # ==========================================================
    def refresh_ui(language):
        ph, hdr, ftr, tips, edu, abt, u = build_interface(language)
        no_hist = f'<p style="color:#163a26;padding:10px;font-size:12px">{u["no_history"]}</p>'
        hint = (f'<div style="padding:10px;color:#304830;font-size:10px">{u["lang_hint"]}</div>')
        ul_lbl  = (f'<div style="color:#3abf8a;font-size:9px;text-transform:uppercase;'
                   f'letter-spacing:1.8px;font-weight:bold;margin-bottom:6px">{u["upload_label"]}</div>')
        res_lbl = (f'<div style="color:#3abf8a;font-size:9px;text-transform:uppercase;'
                   f'letter-spacing:1.8px;font-weight:bold;margin-bottom:6px">{u["result_label"]}</div>')
        ana_lbl = (f'<div style="color:#3abf8a;font-size:9px;text-transform:uppercase;'
                   f'letter-spacing:1.8px;font-weight:bold;padding:8px 0 12px">{u["analytics_title"]}</div>')
        return (hdr(), hint, ul_lbl, res_lbl, ph(), ana_lbl,
                no_hist, tips(), edu(), abt(), ftr(),
                gr.update(value=u["btn_analyze"]),
                gr.update(value=u["btn_clear"]),
                gr.update(label=u["chart_donut"]),
                gr.update(label=u["chart_gauge"]),
                gr.update(label=u["chart_dist"]),
                gr.update(label=u["lang_label"]))

    def run_analysis(up_img, wc_img, lang):
        img = up_img if up_img is not None else wc_img
        return analyze_waste(img, lang)

    def clear_all(language):
        lc=detect_lang(language); u=UI[lc]
        ph=(f'<div style="text-align:center;padding:44px 20px;color:#163a26;'
            f'border:2px dashed #163a26;border-radius:14px">'
            f'<div style="font-size:46px;margin-bottom:10px">🌱</div>'
            f'<div style="font-size:13px">{u["placeholder"]}</div>'
            f'<div style="font-size:10px;margin-top:5px;color:#0f2a1c">{u["placeholder2"]}</div></div>')
        nh=f'<p style="color:#163a26;padding:10px;font-size:12px">{u["no_history"]}</p>'
        return None,None,ph,None,None,None,nh

    # on load
    demo.load(
        fn=refresh_ui, inputs=[language_dd],
        outputs=[header_block, lang_hint_box, upload_lbl, result_lbl, result_display,
                 analytics_lbl, history_display, tips_block, education_block, about_block,
                 footer_block, scan_btn, clear_btn, donut_chart, gauge_chart, dist_chart, language_dd]
    )
    # on language change
    language_dd.change(
        fn=refresh_ui, inputs=[language_dd],
        outputs=[header_block, lang_hint_box, upload_lbl, result_lbl, result_display,
                 analytics_lbl, history_display, tips_block, education_block, about_block,
                 footer_block, scan_btn, clear_btn, donut_chart, gauge_chart, dist_chart, language_dd]
    )
    scan_btn.click(
        fn=run_analysis, inputs=[upload_img, webcam_img, language_dd],
        outputs=[result_display, donut_chart, gauge_chart, dist_chart, history_display]
    )
    clear_btn.click(
        fn=clear_all, inputs=[language_dd],
        outputs=[upload_img, webcam_img, result_display,
                 donut_chart, gauge_chart, dist_chart, history_display]
    )

print("🚀 Launching EcoSort AI v4...")
demo.launch(share=True, debug=False, show_error=True)